# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'apiSearchableApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for apiSearchableApp
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  
  target 'apiSearchableAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'apiSearchableAppUITests' do
    # Pods for testing
  end

end
